### ISSUE TITLE
./make.sh

### ISSUE THREAD

**Issue by Ranchentx** [yqyao/SSD_Pytorch#14]
/make.sh
Error processing line 1 of /home/jnie/anaconda2/envs/pytorch04/lib/python3.6/site-packages/matplotlib-3.0.0-py3.6-nspkg.pth:

Failed to import the site module
Traceback (most recent call last):
  File "/home/jnie/anaconda2/envs/pytorch04/lib/python3.6/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/jnie/anaconda2/envs/pytorch04/lib/python3.6/types.py", line 171, in <module>
    import functools as _functools
  File "/home/jnie/anaconda2/envs/pytorch04/lib/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
ImportError: cannot import name 'namedtuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jnie/anaconda2/envs/pytorch04/lib/python3.6/site.py", line 544, in <module>
    main()
  File "/home/jnie/anaconda2/envs/pytorch04/lib/python3.6/site.py", line 531, in main
    known_paths = addsitepackages(known_paths)
  File "/home/jnie/anaconda2/envs/pytorch04/lib/python3.6/site.py", line 328, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/jnie/anaconda2/envs/pytorch04/lib/python3.6/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/jnie/anaconda2/envs/pytorch04/lib/python3.6/site.py", line 178, in addpackage
    import traceback
  File "/home/jnie/anaconda2/envs/pytorch04/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/home/jnie/anaconda2/envs/pytorch04/lib/python3.6/linecache.py", line 8, in <module>
    import functools
  File "/home/jnie/anaconda2/envs/pytorch04/lib/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
ImportError: cannot import name 'namedtuple'
mv: cannot stat 'nms/cpu_nms.cpython-36m-x86_64-linux-gnu.so': No such file or directory
mv: cannot stat 'nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so': No such file or directory

how to solve it?

**Comment by yqyao** [comment]
maybe you installl collections and delete the line 9 and 10. @Ranchentx

**Comment by Ranchentx** [comment]
when I delete line9 and 10, there still has an error:
ImportError: cannot import name 'namedtuple'
