### ISSUE TITLE
coco

### ISSUE THREAD

**Issue by qq276399331** [yqyao/SSD_Pytorch#15]
我按照提示下载数据环境后，运行出现了no transform_target

**Comment by qq276399331** [comment]
204行 coco.py

**Comment by yqyao** [comment]
我刚更新了 @qq276399331

**Comment by qq276399331** [comment]
～感谢师兄，师兄有15年的dev test数据么 我没找到

**Comment by yqyao** [comment]
这个得从coco官网下了 @qq276399331

**Comment by qq276399331** [comment]
新的问题 当我更新您的代码后，voc2017.py 第320行会报错tuple index out of range

**Comment by yqyao** [comment]
已更新 @qq276399331

**Comment by qq276399331** [comment]
好像coco的方法读写有问题
/pytorch/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [338,0,0], thread: [158,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
^CException ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f7788cc1198>>
Traceback (most recent call last):
  File "/home/lthpc/zhangshichang/pytorch0.4.1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
Process Process-5:
Process Process-6:
    self._shutdown_workers()
Process Process-3:
  File "/home/lthpc/zhangshichang/pytorch0.4.1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 390, in _shutdown_workers
Process Process-1:
    self.worker_result_queue.put(None)
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 354, in put
    with self._wlock:
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt: 
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lthpc/zhangshichang/pytorch0.4.1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 110, in _worker_loop
    data_queue.put((idx, samples))
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 355, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lthpc/zhangshichang/pytorch0.4.1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 110, in _worker_loop
    data_queue.put((idx, samples))
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 354, in put
    with self._wlock:
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lthpc/zhangshichang/pytorch0.4.1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 110, in _worker_loop
    data_queue.put((idx, samples))
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 354, in put
    with self._wlock:
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
  File "/home/lthpc/zhangshichang/pytorch0.4.1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 110, in _worker_loop
    data_queue.put((idx, samples))
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 354, in put
    with self._wlock:
KeyboardInterrupt
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "train.py", line 329, in <module>
    main()
  File "train.py", line 311, in main
    gamma, end_epoch, cfg)
  File "train.py", line 102, in train
    loss_l, loss_c = ssd_criterion(output, targets)
  File "/home/lthpc/zhangshichang/pytorch0.4.1/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lthpc/zhangshichang/resnet_ssd/layers/modules/multibox_loss.py", line 106, in forward
    loss_hard[pos.view(-1, 1)] = 0  # filter out pos boxes for now
RuntimeError: device-side assert triggered

**Comment by qq276399331** [comment]
我对比了您在DRF中的demo.py好像是否少了判断语句

**Comment by qq276399331** [comment]
config我开始就是按照您的方法配置的，我试着去解决这个问题，我觉得是不是数据集中存在空的标记，导致这样的结果

**Comment by qq276399331** [comment]
我训练后，跑demo发现结果并不是很好

**Comment by qq276399331** [comment]
还有个问题我想请教下您，您测fps时怎么测的，batch size是1 么

**Comment by yqyao** [comment]
demo.py 那个可以按照需求来改，fps 测得是batch的方式，我测试的是batch=32时的情况 @qq276399331 另外我只算forward的时间

**Comment by qq276399331** [comment]
您有这方面的代码么，我的意思是跑demo的时候的batchsize 是设置成32 么

**Comment by qq276399331** [comment]
我发现 coco跑的50代的结果 并没有map的计算结果。

**Comment by yqyao** [comment]
讲道理是不会这样的，你看看结果文件生成了没 @qq276399331

**Comment by qq276399331** [comment]
我看错了,,结果生成的是不同IOU的AP 和dssd论文中指标一样

**Comment by qq276399331** [comment]
而且好像官网已经关闭了coco2015test_dev了

**Comment by yqyao** [comment]
可以用2017的吧，图片是一样的 @qq276399331

**Comment by qq276399331** [comment]
2017的和2014的训练集是一样的么？训练有影响么会

**Comment by qq276399331** [comment]
师兄有跑过coco么

**Comment by yqyao** [comment]
影响不大 @qq276399331

**Comment by qq276399331** [comment]
我试着将您的代码迁移到1.0版本但是出现了 cuda runtime error(11):invalid argument 错误，您有什么见解么

**Comment by qq276399331** [comment]
师兄设置的训练集是2014train和 valminusminival2014 annotations一起的吧，这样不会有问题么，我怎么看许多论文都是值用train 35k来训练呢

**Comment by yqyao** [comment]
我没有试过。。@qq276399331

**Comment by qq276399331** [comment]
您好又来打扰您了，我想问下我看test代码是batch是16我用测试消耗的时间去除总的图片数量得到的可以认作是FPS么
