### ISSUE TITLE
TypeError in refine_multibox_loss.py. maybe a bug

### ISSUE THREAD

**Issue by haochange** [yqyao/SSD_Pytorch#19]
Traceback (most recent call last):
  File "train.py", line 334, in <module>
    main()
  File "train.py", line 314, in main
    gamma, end_epoch, cfg)
  File "train.py", line 111, in train
    output, targets, use_arm=True, filter_object=True)
  File "/home/ubuntu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/SSD_Pytorch/layers/modules/refine_multibox_loss.py", line 154, in forward
    max=pos.size(1) - 1)
TypeError: clamp(): argument 'input' (position 1) must be Tensor, not int

**Comment by yqyao** [comment]
I have updated some codes to solve this problem. @haochange

**Comment by haochange** [comment]
> 
> 
> I have updated some codes to solve this problem. @haochange

Thank you so much！

**Comment by Ranchentx** [comment]
@PCML-WangZhe  Do you solve the problem? I meet the same problem
