### ISSUE TITLE
when i make the make.sh file,there is a error

### ISSUE THREAD

**Issue by whao246** [yqyao/SSD_Pytorch#23]
`Error processing line 1 of /home/whao/anaconda3/envs/torch/lib/python3.6/site-packages/matplotlib-3.0.2-py3.6-nspkg.pth:

Failed to import the site module
Traceback (most recent call last):
  File "/home/whao/anaconda3/envs/torch/lib/python3.6/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/whao/anaconda3/envs/torch/lib/python3.6/types.py", line 171, in <module>
    import functools as _functools
  File "/home/whao/anaconda3/envs/torch/lib/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
ImportError: cannot import name 'namedtuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/whao/anaconda3/envs/torch/lib/python3.6/site.py", line 550, in <module>
    main()
  File "/home/whao/anaconda3/envs/torch/lib/python3.6/site.py", line 532, in main
    known_paths = addsitepackages(known_paths)
  File "/home/whao/anaconda3/envs/torch/lib/python3.6/site.py", line 320, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/whao/anaconda3/envs/torch/lib/python3.6/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/whao/anaconda3/envs/torch/lib/python3.6/site.py", line 178, in addpackage
    import traceback
  File "/home/whao/anaconda3/envs/torch/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/home/whao/anaconda3/envs/torch/lib/python3.6/linecache.py", line 8, in <module>
    import functools
  File "/home/whao/anaconda3/envs/torch/lib/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
ImportError: cannot import name 'namedtuple'
mv: 无法获取'nms/cpu_nms.cpython-36m-x86_64-linux-gnu.so' 的文件状态(stat): 没有那个文件或目录
mv: 无法获取'nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so' 的文件状态(stat): 没有那个文件或目录
`

**Comment by whao246** [comment]
I also have changed  the code like https://github.com/rbgirshick/py-faster-rcnn/issues/706

**Comment by yqyao** [comment]
try to delete it? @whao246

**Comment by whao246** [comment]
> try to delete it? @whao246
delete the make.sh  file?@yqyao

**Comment by yqyao** [comment]
delete mv nms/cpu_nms.cpython-36m-x86_64-linux-gnu.so nms/cpu_nms.so
mv nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so nms/gpu_nms.so @whao246
