### ISSUE TITLE
About test your code

### ISSUE THREAD

**Issue by ylc2580** [yqyao/SSD_Pytorch#33]
hi,
    when I run your test code, I meet this,
 Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from data import COCODetection, VOCDetection, detection_collate, BaseTransform, preproc
  File "D:\SSD\Pytorch\SSD_Pytorch-master\SSD_Pytorch-master\data\__init__.py", line 4, in <module>
    from .data_augment import *
  File "D:\SSD\Pytorch\SSD_Pytorch-master\SSD_Pytorch-master\data\data_augment.py", line 18, in <module>
    from utils.box_utils import matrix_iou
  File "D:\SSD\Pytorch\SSD_Pytorch-master\SSD_Pytorch-master\utils\box_utils.py", line 6, in <module>
    from utils.nms.cpu_nms import get_iou_weights, get_mask
ModuleNotFoundError: No module named 'utils.nms.cpu_nms'
    could you tell me how to deal?
    And I used your code in windows.thank you very much!

**Comment by yqyao** [comment]
do you run the ./make.sh? @ylc2580
